PingPong/urls.py
from django.contrib import admin
from django.urls import path, include
from PingPong import views

urlpatterns = [
    path('home/', views.index),
    path('players/', include('players.urls')),
    path('referee/', include('referee.urls')),
    path('admin/', admin.site.urls),
]

players/urls.py
from django.urls import path
from . import views

app_name = "players"
urlpatterns = [
    path('', views.index, name='index'),
    path('create_player/', views.create_player, name='create_player'),
    path('join_game/', views.join_game, name='join_game'),
]

players/models.py
from django.db import models
# Create your models here.


class Players(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    array_length = models.IntegerField(default=0)
    is_active = models.BooleanField(default=False)

    @staticmethod
    def active_players_count():
        return Players.objects.filter(is_active=True).count()

    @staticmethod
    def get_active_players():
        return Players.objects.filter(is_active=True)

    @staticmethod
    def get_player_by_id(id):
        return Players.objects.filter(id=id)

    def set_inactive(self):
        Players.objects.filter(id=self.id).update(is_active=False)

players/views.py
from django.shortcuts import render
from .models import Players
# Create your views here.


def index(request):
    return render(request, 'players/index.html')


def create_player(request):
    if request.method == 'POST':
        player = request.POST
        if not Players.objects.filter(username=player['username']).exists():
            Players.objects.create(username=player['username'], password=player['password'])
            return render(request, 'players/index.html', context={'message': 'Player added'})
        else:
            return render(request, 'players/create_player.html', context={'message': 'Player already exist'})
    else:
        return render(request, 'players/create_player.html')


def join_game(request):
    if request.method == 'POST':
        player = request.POST
        if Players.objects.filter(username=player['username'], password=player['password']).exists():
            Players.objects.select_for_update().filter(username=player['username']).update(array_length=player['array_length'], is_active=True)
            return render(request, 'players/index.html', context={'message': 'Player added to the game'})
        return render(request, 'players/join_game.html', context={'message': 'Invalid user details'})
    else:
        return render(request, 'players/join_game.html')

players/templates/players/create_player.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Player</title>
    <script>
        {% if message %}
            alert('{{ message }}')
        {% endif %}
    </script>
</head>
<body>
    <form action="{% url 'players:create_player' %}" method="post">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" id="id_username" required/><br>
        <label>Password</label>
        <input type="password" name="password" id="id_password" required/><br>
        <input type="submit" value="Create">
    </form>
</body>
</html>

players/templates/players/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ping Pong</title>
    <script>
        {% if message %}
            alert('{{ message }}')
        {% endif %}
    </script>
</head>
<body>
    <a href="{% url 'players:create_player' %}"><input type="button" id="id_create" value="Create Player"/></a>
    <a href="{% url 'players:join_game' %}"><input type="button" value="Join Game"/></a>
</body>
</html>

players/templates/players/join_game.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Join Game</title>
    <script>
        {% if message %}
            alert('{{ message }}')
        {% endif %}
    </script>
</head>
<body>
    <form action="{% url 'players:join_game' %}" method="post">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="username" id="id_username" required/><br>
        <label>Password</label>
        <input type="password" name="password" id="id_password" required/><br>
        <label>Pick a random number : </label>
        <input type="number" name="array_length" id="id_array_length" min="1" max="10" required/><br>
        <input type="submit" value="Create">
    </form>
</body>
</html>